spring.application.name=maintenance-tracker-backend
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/maintenance-tracker
spring.datasource.username=maintenance-tracker
spring.datasource.password=maintenance-tracker
server.port=9090